name: tests

on:
  push:
    branches:
      - not-a-branch
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-load-graph:
    name: tests-load-graph
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: cf-graph

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: conda-forge/conda-forge-bot
          path: cf-scripts

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: conda-forge/conda-forge-pinning-feedstock
          path: conda-forge-pinning-feedstock

      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-file: cf-scripts/conda-lock.yml
          environment-name: cf-scripts
          condarc-file: cf-scripts/autotick-bot/condarc

      - name: install bot code
        run: |
          git config --global user.name regro-cf-autotick-bot
          git config --global user.email 36490558+regro-cf-autotick-bot@users.noreply.github.com
          git config --global pull.rebase false

          pushd cf-scripts
          python -m pip install --no-deps --no-build-isolation -e .
          popd

      - name: load graph
        run: |
          pushd cf-graph
          pytest -vv test_load_graph.py
          popd

  tests-model:
    name: tests-model
    continue-on-error: true
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: cf-graph

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: conda-forge/conda-forge-bot
          path: cf-scripts

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: conda-forge/conda-forge-pinning-feedstock
          path: conda-forge-pinning-feedstock

      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-file: cf-scripts/conda-lock.yml
          environment-name: cf-scripts
          condarc-file: cf-scripts/autotick-bot/condarc

      - name: install bot code
        run: |
          git config --global user.name regro-cf-autotick-bot
          git config --global user.email 36490558+regro-cf-autotick-bot@users.noreply.github.com
          git config --global pull.rebase false

          pushd cf-scripts
          python -m pip install --no-deps --no-build-isolation -e .
          popd

      - name: check graph model
        run: |
          pushd cf-graph
          pytest \
            --durations 10 \
            ../cf-scripts/tests_model
          popd
